require("dotenv").config();
const { Client } = require("pg");
const cds = require("@sap/cds");

cds.env.requires.db = {
  kind: "postgres",
  credentials: {
    host: process.env.DB_HOST,
    port: parseInt(process.env.DB_PORT),
    database: process.env.DB_NAME,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    ssl: { rejectUnauthorized: false },
  },
  schema_evolution: "off",
};

cds.env.sql = {
  native_hana_types: false,
  sql_mapping: "plain",
};

cds.env["schema_evolution"] = "off";

// ─────────────────────────────────────────────────────────────────────────────
// UNIQUE CONSTRAINTS
// Add an entry here whenever you need a unique constraint on a table.
// Format: { table: "db_table_name", name: "constraint_name", cols: "col1, col2" }
// ─────────────────────────────────────────────────────────────────────────────
const UNIQUE_CONSTRAINTS = [
  { table: "crm_modules", name: "uq_modules_name", cols: "name" },
  { table: "crm_permissions", name: "uq_permissions_name", cols: "name" },
  { table: "crm_roles", name: "uq_roles_name", cols: "name" },
  { table: "crm_organization", name: "uq_organization_code", cols: "code" },
  { table: "crm_leads", name: "uq_leads_code", cols: "code" },
  { table: "crm_offer", name: "uq_offer_code", cols: "code" },
  {
    table: "crm_modulepermissions",
    name: "uq_module_permissions",
    cols: "module_ID, permission_ID",
  },
  {
    table: "crm_rolemodulepermissions",
    name: "uq_role_module_perms",
    cols: "role_ID, module_permission_ID",
  },
  {
    table: "crm_organizationroles",
    name: "uq_org_roles",
    cols: "organization_ID, role_ID",
  },
  {
    table: "crm_organizationmodules",
    name: "uq_org_modules",
    cols: "organization_ID, module_ID",
  },
  {
    table: "crm_organizationrolemodulepermissions",
    name: "uq_org_role_rmp",
    cols: "organizationRole_ID, rmp_ID",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SYSTEM TABLES — never touched by migrate, owned by CDS/SAP internally
// ─────────────────────────────────────────────────────────────────────────────
const SYSTEM_TABLES = new Set([
  "cds_model",
  "sap_common_languages",
  "sap_common_languages_texts",
  "sap_common_countries",
  "sap_common_countries_texts",
  "sap_common_currencies",
  "sap_common_currencies_texts",
  "sap_common_timezones",
  "sap_common_timezones_texts",
  "_migrations",
]);

// ─────────────────────────────────────────────────────────────────────────────
// SYSTEM COLUMNS — auto-generated by cuid/managed mixins, never drop these
// ─────────────────────────────────────────────────────────────────────────────
const SYSTEM_COLUMNS = new Set([
  "id",
  "createdat",
  "createdby",
  "modifiedat",
  "modifiedby",
]);

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

// Build expected DB columns for a CDS entity.
// Key insight from debug: isAssociation/isComposition flags are always undefined
// in cds-compiler v6. Instead we check:
//   type === 'cds.Association' + keys set  → forward FK  → colName_id column
//   type === 'cds.Composition' + on set    → backlink    → no DB column
//   anything else with a type              → scalar      → direct column
function getExpectedColumns(entity) {
  const cols = new Set();
  for (const [colName, element] of Object.entries(entity.elements || {})) {
    if (element.virtual) continue;
    if (element.type === "cds.Composition") continue; // never a DB column
    if (element.type === "cds.Association") {
      if (element.keys) {
        // Forward association → FK column
        cols.add((colName + "_id").toLowerCase());
      }
      // If no keys (backlink with 'on') → no DB column, skip
    } else if (element.type) {
      // Scalar field → real DB column
      cols.add(colName.toLowerCase());
    }
  }
  return cols;
}

function getCdsTableNames(model) {
  const names = new Set();
  for (const [name, def] of Object.entries(model.definitions)) {
    if (def.kind !== "entity") continue;
    if (def["@cds.persistence.skip"]) continue;
    names.add(name.replace(/\./g, "_").toLowerCase());
  }
  return names;
}

async function getActualTables(client) {
  const { rows } = await client.query(`
    SELECT table_name FROM information_schema.tables
    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
  `);
  return new Set(rows.map((r) => r.table_name));
}

async function getTableColumns(client, table) {
  const { rows } = await client.query(
    `
    SELECT column_name FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = $1
  `,
    [table],
  );
  return new Set(rows.map((r) => r.column_name));
}

async function getIncomingFKs(client, table) {
  const { rows } = await client.query(
    `
    SELECT tc.table_name AS referencing_table, kcu.column_name AS referencing_column
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
      ON tc.constraint_name = kcu.constraint_name
    JOIN information_schema.constraint_column_usage AS ccu
      ON ccu.constraint_name = tc.constraint_name
    WHERE tc.constraint_type = 'FOREIGN KEY' AND ccu.table_name = $1
  `,
    [table],
  );
  return rows;
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 1 — Drop removed tables BEFORE CDS deploy
// Must happen first because CDS compiler throws if it detects a removed entity
// that still exists in the DB. We drop it manually so CDS never sees it.
// ─────────────────────────────────────────────────────────────────────────────
async function dropRemovedTables(client, model) {
  console.log("\n[1/5] Checking for removed tables...");
  let drops = 0;

  const cdsTableNames = getCdsTableNames(model);
  const actualTables = await getActualTables(client);

  for (const table of actualTables) {
    if (SYSTEM_TABLES.has(table)) continue;
    if (!table.startsWith("crm_")) continue; // only manage your namespace
    if (cdsTableNames.has(table)) continue; // still in schema, keep it

    // Check for incoming FK references — skip if other tables depend on this one
    const fks = await getIncomingFKs(client, table);
    if (fks.length > 0) {
      const refs = fks
        .map((r) => `${r.referencing_table}.${r.referencing_column}`)
        .join(", ");
      console.log(
        `  ⚠️  Skipping drop of ${table} — still referenced by: ${refs}`,
      );
      continue;
    }

    console.log(`  🗑️  Dropping removed table: ${table}`);
    try {
      await client.query(`DROP TABLE IF EXISTS "${table}" CASCADE`);
      drops++;
    } catch (e) {
      console.warn(`  ⚠️  Could not drop ${table}: ${e.message.trim()}`);
    }
  }

  if (drops === 0) console.log("  ✅ No tables to drop.");
  else console.log(`  ✅ ${drops} table(s) dropped.`);
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 2 — Detect new tables (CDS deploy will create them)
// ─────────────────────────────────────────────────────────────────────────────
async function detectNewTables(client, model) {
  console.log("\n[2/5] Checking for new tables...");

  const cdsTableNames = getCdsTableNames(model);
  const actualTables = await getActualTables(client);
  let newCount = 0;

  for (const table of cdsTableNames) {
    if (!table.startsWith("crm_")) continue;
    if (!actualTables.has(table)) {
      console.log(`  ➕ New table will be created: ${table}`);
      newCount++;
    }
  }

  if (newCount === 0) console.log("  ✅ No new tables.");
  else
    console.log(`  ✅ ${newCount} new table(s) will be created by CDS deploy.`);
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 3 — Sync columns
// Drops columns removed from schema.
// Logs new columns (CDS deploy adds them automatically).
// Never touches system columns (id, createdAt, createdBy, etc.)
// ─────────────────────────────────────────────────────────────────────────────
async function syncColumns(client, model) {
  console.log("\n[3/5] Diffing columns...");
  let drops = 0;
  let additions = 0;
  let skipped = 0;

  const actualTables = await getActualTables(client);

  for (const [name, entity] of Object.entries(model.definitions)) {
    if (entity.kind !== "entity") continue;
    if (entity["@cds.persistence.skip"]) continue;

    const table = name.replace(/\./g, "_").toLowerCase();
    if (!actualTables.has(table)) continue; // new table — handled by CDS deploy

    const actualCols = await getTableColumns(client, table);
    const expectedCols = getExpectedColumns(entity);

    // Safety: if expected is empty something went wrong — skip this table
    if (expectedCols.size === 0) {
      console.log(
        `  ⚠️  Skipping ${table} — could not resolve expected columns`,
      );
      skipped++;
      continue;
    }

    // Log new columns (CDS deploy will add them)
    for (const col of expectedCols) {
      if (SYSTEM_COLUMNS.has(col)) continue;
      if (!actualCols.has(col)) {
        console.log(`  ➕ New column will be added: ${table}.${col}`);
        additions++;
      }
    }

    // Drop removed columns
    for (const col of actualCols) {
      if (SYSTEM_COLUMNS.has(col)) continue;
      if (expectedCols.has(col)) continue;

      console.log(`  🗑️  Dropping column: ${table}.${col}`);
      try {
        await client.query(
          `ALTER TABLE "${table}" DROP COLUMN IF EXISTS "${col}"`,
        );
        drops++;
      } catch (e) {
        console.warn(
          `  ⚠️  Could not drop ${table}.${col}: ${e.message.trim()}`,
        );
      }
    }
  }

  if (drops === 0 && additions === 0 && skipped === 0) {
    console.log("  ✅ No column changes needed.");
  } else {
    if (additions > 0)
      console.log(
        `  ✅ ${additions} new column(s) will be added by CDS deploy.`,
      );
    if (drops > 0) console.log(`  ✅ ${drops} column(s) dropped.`);
    if (skipped > 0)
      console.log(`  ⚠️  ${skipped} table(s) skipped for safety.`);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 4 — CDS deploy
// Creates new tables, adds new columns, fixes column types.
// We catch the specific "Dropping tables is not supported" error because:
//   - We already dropped removed tables manually in Step 1
//   - CDS compiler still complains if it detects a removed entity in the model
//   - It's safe to ignore this specific error only
// ─────────────────────────────────────────────────────────────────────────────
async function runCdsDeploy(model) {
  console.log("\n[4/5] Running CDS deploy...");
  try {
    const db = await cds.connect.to("db");
    await cds.deploy(model).to(db);
    console.log("  ✅ CDS deploy done!");
  } catch (e) {
    if (e.message.includes("Dropping tables is not supported")) {
      // Safe to ignore — we already dropped the table manually in Step 1
      console.log("  ✅ CDS deploy done! (removed tables handled manually)");
    } else {
      throw e; // re-throw any other real errors
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 5 — Apply unique constraints
// Skips constraints that already exist.
// ─────────────────────────────────────────────────────────────────────────────
async function applyUniqueConstraints(client) {
  console.log("\n[5/5] Applying unique constraints...");
  for (const { table, name, cols } of UNIQUE_CONSTRAINTS) {
    try {
      await client.query(
        `ALTER TABLE "${table}" ADD CONSTRAINT ${name} UNIQUE (${cols})`,
      );
      console.log(`  ✅ ${name}`);
    } catch (e) {
      if (e.message.includes("already exists")) {
        console.log(`  ⏭️  ${name} already exists, skipping`);
      } else {
        console.warn(`  ⚠️  ${name} failed: ${e.message.trim()}`);
      }
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────────────────────────────────────
async function main() {
  const client = new Client({
    host: process.env.DB_HOST,
    port: parseInt(process.env.DB_PORT),
    database: process.env.DB_NAME,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    ssl: { rejectUnauthorized: false },
  });

  await client.connect();

  console.log("Loading CDS model...");
  const model = await cds.load(["db/schema.cds", "srv/service.cds"]);
  console.log("Reading current DB schema...");

  await dropRemovedTables(client, model); // Step 1 — must be before CDS deploy
  await detectNewTables(client, model); // Step 2 — informational
  await syncColumns(client, model); // Step 3 — drop removed columns
  await runCdsDeploy(model); // Step 4 — create/update via CDS
  await applyUniqueConstraints(client); // Step 5 — enforce uniqueness

  await client.end();
  console.log("\n✅ Migration complete — no data lost!");
  process.exit(0);
}

main().catch((e) => {
  console.error("\nFAILED:", e.message);
  process.exit(1);
});
