require("dotenv").config();
const { Client } = require("pg");
const cds = require("@sap/cds");

cds.env.requires.db = {
  kind: "postgres",
  credentials: {
    host: process.env.DB_HOST,
    port: parseInt(process.env.DB_PORT),
    database: process.env.DB_NAME,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    ssl: { rejectUnauthorized: false },
  },
  schema_evolution: "off",
};

cds.env.sql = {
  native_hana_types: false,
  sql_mapping: "plain",
};

cds.env["schema_evolution"] = "off";

// ─────────────────────────────────────────────────────────────────────────────
// UNIQUE CONSTRAINTS
// Add an entry here whenever you need a unique constraint on a table.
// Format: { table: "db_table_name", name: "constraint_name", cols: "col1, col2" }
// ─────────────────────────────────────────────────────────────────────────────
const UNIQUE_CONSTRAINTS = [
  { table: "crm_modules", name: "uq_modules_name", cols: "name" },
  { table: "crm_permissions", name: "uq_permissions_name", cols: "name" },
  { table: "crm_roles", name: "uq_roles_name", cols: "name" },
  { table: "crm_organization", name: "uq_organization_code", cols: "code" },
  { table: "crm_leads", name: "uq_leads_code", cols: "code" },
  { table: "crm_offer", name: "uq_offer_code", cols: "code" },
  {
    table: "crm_modulepermissions",
    name: "uq_module_permissions",
    cols: "module_ID, permission_ID",
  },
  {
    table: "crm_rolemodulepermissions",
    name: "uq_role_module_perms",
    cols: "role_ID, module_permission_ID",
  },
  {
    table: "crm_organizationroles",
    name: "uq_org_roles",
    cols: "organization_ID, role_ID",
  },
  {
    table: "crm_organizationmodules",
    name: "uq_org_modules",
    cols: "organization_ID, module_ID",
  },
  {
    table: "crm_organizationrolemodulepermissions",
    name: "uq_org_role_rmp",
    cols: "organizationRole_ID, rmp_ID",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SYSTEM TABLES — never touched by migrate, owned by CDS/SAP internally
// ─────────────────────────────────────────────────────────────────────────────
const SYSTEM_TABLES = new Set([
  "cds_model",
  "sap_common_languages",
  "sap_common_languages_texts",
  "sap_common_countries",
  "sap_common_countries_texts",
  "sap_common_currencies",
  "sap_common_currencies_texts",
  "sap_common_timezones",
  "sap_common_timezones_texts",
  "_migrations",
]);

// ─────────────────────────────────────────────────────────────────────────────
// SYSTEM COLUMNS — auto-generated by cuid/managed mixins, never drop these
// ─────────────────────────────────────────────────────────────────────────────
const SYSTEM_COLUMNS = new Set([
  "id",
  "createdat",
  "createdby",
  "modifiedat",
  "modifiedby",
]);

// ─────────────────────────────────────────────────────────────────────────────
// CDS type → SQL type mapping
// Covers scalars + falls back to VARCHAR for named enum types
// ─────────────────────────────────────────────────────────────────────────────
function cdsTypeToSql(type) {
  const map = {
    "cds.String": "VARCHAR(5000)",
    "cds.LargeString": "TEXT",
    "cds.Integer": "INTEGER",
    "cds.Integer64": "BIGINT",
    "cds.Decimal": "DECIMAL",
    "cds.Double": "DOUBLE PRECISION",
    "cds.Boolean": "BOOLEAN",
    "cds.Date": "DATE",
    "cds.Time": "TIME",
    "cds.DateTime": "TIMESTAMP",
    "cds.Timestamp": "TIMESTAMP",
    "cds.UUID": "VARCHAR(36)",
  };
  return map[type] || "VARCHAR(5000)"; // enums are String-based → VARCHAR
}

// ─────────────────────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────────────────────

// Build expected DB columns for a CDS entity.
// Key insight from debug: isAssociation/isComposition flags are always undefined
// in cds-compiler v6. Instead we check:
//   type === 'cds.Association' + keys set  → forward FK  → colName_id column
//   type === 'cds.Composition' + on set    → backlink    → no DB column
//   anything else with a type              → scalar      → direct column
function getExpectedColumns(entity) {
  const cols = new Set();
  for (const [colName, element] of Object.entries(entity.elements || {})) {
    if (element.virtual) continue;
    if (element.type === "cds.Composition") continue;
    if (element.type === "cds.Association") {
      if (element.keys) cols.add((colName + "_id").toLowerCase());
    } else if (element.type) {
      cols.add(colName.toLowerCase());
    }
  }
  return cols;
}

function getCdsTableNames(model) {
  const names = new Set();
  for (const [name, def] of Object.entries(model.definitions)) {
    if (def.kind !== "entity") continue;
    if (def["@cds.persistence.skip"]) continue;
    names.add(name.replace(/\./g, "_").toLowerCase());
  }
  return names;
}

async function getActualTables(client) {
  const { rows } = await client.query(`
    SELECT table_name FROM information_schema.tables
    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
  `);
  return new Set(rows.map((r) => r.table_name));
}

async function getTableColumns(client, table) {
  const { rows } = await client.query(
    `SELECT column_name FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = $1`,
    [table],
  );
  return new Set(rows.map((r) => r.column_name));
}

async function getIncomingFKs(client, table) {
  const { rows } = await client.query(
    `SELECT tc.table_name AS referencing_table, kcu.column_name AS referencing_column
     FROM information_schema.table_constraints AS tc
     JOIN information_schema.key_column_usage AS kcu
       ON tc.constraint_name = kcu.constraint_name
     JOIN information_schema.constraint_column_usage AS ccu
       ON ccu.constraint_name = tc.constraint_name
     WHERE tc.constraint_type = 'FOREIGN KEY' AND ccu.table_name = $1`,
    [table],
  );
  return rows;
}

// ─────────────────────────────────────────────────────────────────────────────
// Resolve the SQL type for any CDS element, including named enum types.
// e.g.  trial: TrailType  →  model.definitions["crm.TrailType"].type = "cds.String"
//                          →  cdsTypeToSql("cds.String") = "VARCHAR(5000)"
// ─────────────────────────────────────────────────────────────────────────────
function resolveSqlType(element, model) {
  if (element.type === "cds.Association") return "VARCHAR(36)";

  // Named type reference (e.g. "crm.TrailType")
  const resolved = model.definitions[element.type];
  if (resolved) {
    // Enum types have a base `type` like "cds.String"
    return cdsTypeToSql(resolved.type || "cds.String");
  }

  // length annotation on String → VARCHAR(n)
  if (element.type === "cds.String" && element.length) {
    return `VARCHAR(${element.length})`;
  }

  return cdsTypeToSql(element.type);
}

// ─────────────────────────────────────────────────────────────────────────────
// Builds a minimal but accurate CSN from actual DB tables/columns.
// This tells CDS "these tables already exist" so it won't try to CREATE them.
// Used when cds_model is empty to avoid the "Cannot read properties of undefined"
// crash that happens when CDS tries to read a non-existent csn row.
// ─────────────────────────────────────────────────────────────────────────────
async function buildCsnFromDb(client, model) {
  const definitions = {};

  for (const [name, def] of Object.entries(model.definitions)) {
    if (def.kind !== "entity") continue;
    if (def["@cds.persistence.skip"]) continue;

    const table = name.replace(/\./g, "_").toLowerCase();

    const { rows: tableRows } = await client.query(
      `SELECT COUNT(*) as count FROM information_schema.tables
       WHERE table_schema = 'public' AND table_name = $1`,
      [table],
    );
    if (tableRows[0].count === "0") continue; // table doesn't exist yet

    const { rows: colRows } = await client.query(
      `SELECT column_name FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = $1`,
      [table],
    );
    const dbCols = new Set(colRows.map((r) => r.column_name));

    const elements = {};
    for (const [colName, element] of Object.entries(def.elements || {})) {
      if (element.virtual) continue;
      if (element.type === "cds.Composition") continue;

      if (element.type === "cds.Association") {
        if (!element.keys) continue;
        const fkCol = (colName + "_id").toLowerCase();
        if (dbCols.has(fkCol)) {
          elements[colName] = {
            type: "cds.Association",
            target: element.target,
            keys: element.keys,
          };
          elements[colName + "_ID"] = { type: "cds.String", length: 36 };
        }
      } else if (element.type) {
        const dbCol = colName.toLowerCase();
        if (dbCols.has(dbCol)) {
          elements[colName] = { type: element.type };
          if (element.length) elements[colName].length = element.length;
        }
      }
    }

    definitions[name] = {
      kind: "entity",
      elements,
      "@cds.persistence.name": table.toUpperCase(),
    };
  }

  return {
    $version: "2.0",
    definitions,
    meta: { creator: "deploy-migrate.js bootstrap", flavor: "inferred" },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 1 — Drop removed tables BEFORE CDS deploy
// Must happen first because CDS compiler throws if it detects a removed entity
// that still exists in the DB. We drop it manually so CDS never sees it.
// ─────────────────────────────────────────────────────────────────────────────
async function dropRemovedTables(client, model) {
  console.log("\n[1/6] Checking for removed tables...");
  let drops = 0;

  const cdsTableNames = getCdsTableNames(model);
  const actualTables = await getActualTables(client);

  for (const table of actualTables) {
    if (SYSTEM_TABLES.has(table)) continue;
    if (!table.startsWith("crm_")) continue; // only manage your namespace
    if (cdsTableNames.has(table)) continue; // still in schema, keep it

    // Check for incoming FK references — skip if other tables depend on this one
    const fks = await getIncomingFKs(client, table);
    if (fks.length > 0) {
      const refs = fks
        .map((r) => `${r.referencing_table}.${r.referencing_column}`)
        .join(", ");
      console.log(
        `  ⚠️  Skipping drop of ${table} — still referenced by: ${refs}`,
      );
      continue;
    }

    console.log(`  🗑️  Dropping removed table: ${table}`);
    try {
      await client.query(`DROP TABLE IF EXISTS "${table}" CASCADE`);
      drops++;
    } catch (e) {
      console.warn(`  ⚠️  Could not drop ${table}: ${e.message.trim()}`);
    }
  }

  if (drops === 0) console.log("  ✅ No tables to drop.");
  else console.log(`  ✅ ${drops} table(s) dropped.`);
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 2 — Detect new tables (CDS deploy will create them)
// ─────────────────────────────────────────────────────────────────────────────
async function detectNewTables(client, model) {
  console.log("\n[2/6] Checking for new tables...");

  const cdsTableNames = getCdsTableNames(model);
  const actualTables = await getActualTables(client);
  let newCount = 0;

  for (const table of cdsTableNames) {
    if (!table.startsWith("crm_")) continue;
    if (!actualTables.has(table)) {
      console.log(`  ➕ New table will be created: ${table}`);
      newCount++;
    }
  }

  if (newCount === 0) console.log("  ✅ No new tables.");
  else
    console.log(`  ✅ ${newCount} new table(s) will be created by CDS deploy.`);
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 3 — Sync columns
// Drops columns removed from schema.
// Logs new columns (CDS deploy adds them automatically).
// Never touches system columns (id, createdAt, createdBy, etc.)
// ─────────────────────────────────────────────────────────────────────────────
async function syncColumns(client, model) {
  console.log("\n[3/6] Diffing columns...");
  let drops = 0;
  let additions = 0;
  let skipped = 0;

  const actualTables = await getActualTables(client);

  for (const [name, entity] of Object.entries(model.definitions)) {
    if (entity.kind !== "entity") continue;
    if (entity["@cds.persistence.skip"]) continue;

    const table = name.replace(/\./g, "_").toLowerCase();
    if (!actualTables.has(table)) continue; // new table — handled by CDS deploy

    const actualCols = await getTableColumns(client, table);
    const expectedCols = getExpectedColumns(entity);

    // Safety: if expected is empty something went wrong — skip this table
    if (expectedCols.size === 0) {
      console.log(
        `  ⚠️  Skipping ${table} — could not resolve expected columns`,
      );
      skipped++;
      continue;
    }

    for (const col of expectedCols) {
      if (SYSTEM_COLUMNS.has(col)) continue;
      if (!actualCols.has(col)) {
        console.log(`  ➕ New column will be added: ${table}.${col}`);
        additions++;
      }
    }

    // Drop removed columns
    for (const col of actualCols) {
      if (SYSTEM_COLUMNS.has(col)) continue;
      if (expectedCols.has(col)) continue;

      console.log(`  🗑️  Dropping column: ${table}.${col}`);
      try {
        await client.query(
          `ALTER TABLE "${table}" DROP COLUMN IF EXISTS "${col}"`,
        );
        drops++;
      } catch (e) {
        console.warn(
          `  ⚠️  Could not drop ${table}.${col}: ${e.message.trim()}`,
        );
      }
    }
  }

  if (drops === 0 && additions === 0 && skipped === 0) {
    console.log("  ✅ No column changes needed.");
  } else {
    if (additions > 0)
      console.log(
        `  ✅ ${additions} new column(s) will be added by CDS deploy.`,
      );
    if (drops > 0) console.log(`  ✅ ${drops} column(s) dropped.`);
    if (skipped > 0)
      console.log(`  ⚠️  ${skipped} table(s) skipped for safety.`);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 4 — Patch CDS model cache
// cds_model.csn stores the last deployed model.
// If empty  → BUILD CSN from actual DB state so CDS knows what already exists.
//             Empty table causes crash: "Cannot read properties of undefined"
// If exists → Remove stale entity definitions so CDS sees no dropped tables.
// ─────────────────────────────────────────────────────────────────────────────
async function patchCdsModelCache(client, model) {
  console.log("\n[4/6] Patching CDS model cache...");
  try {
    const tableCheck = await client.query(`
      SELECT COUNT(*) as count FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = 'cds_model'
    `);

    if (tableCheck.rows[0].count === "0") {
      console.log("  ✅ No CDS model cache table found, skipping.");
      return;
    }

    const countCheck = await client.query(
      `SELECT COUNT(*) as count FROM cds_model`,
    );
    const rowCount = parseInt(countCheck.rows[0].count);

    if (rowCount === 0) {
      // Empty — build from actual DB state so CDS doesn't try to CREATE existing tables
      const csn = await buildCsnFromDb(client, model);
      await client.query(`INSERT INTO cds_model (csn) VALUES ($1)`, [
        JSON.stringify(csn),
      ]);
      console.log("  ✅ CDS model cache bootstrapped from current DB state.");
      return;
    }

    // Row exists — remove stale entity definitions
    const { rows } = await client.query(`SELECT csn FROM cds_model LIMIT 1`);
    const existingCsn = JSON.parse(rows[0].csn);

    // Get current entity names from the live model
    const currentEntityNames = new Set(
      Object.keys(model.definitions).filter(
        (k) => model.definitions[k].kind === "entity",
      ),
    );

    // Remove definitions from stored CSN that no longer exist in current model
    // This stops CDS from seeing "dropped" entities and throwing errors
    let patched = false;
    for (const key of Object.keys(existingCsn.definitions || {})) {
      if (
        !currentEntityNames.has(key) &&
        existingCsn.definitions[key].kind === "entity"
      ) {
        delete existingCsn.definitions[key];
        console.log(`  🗑️  Removed stale entity from cache: ${key}`);
        patched = true;
      }
    }

    if (patched) {
      await client.query(`UPDATE cds_model SET csn = $1`, [
        JSON.stringify(existingCsn),
      ]);
      console.log("  ✅ CDS model cache patched.");
    } else {
      console.log("  ✅ CDS model cache is already up to date.");
    }
  } catch (e) {
    console.log(`  ⚠️  Could not patch CDS model cache: ${e.message.trim()}`);
    console.log("  Continuing anyway...");
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 5 — CDS deploy + raw SQL fallback for enum type bug
//
// CDS compiler throws "Unexpected non-primitive type" when a named enum type
// (e.g. TrailType, Gender) appears during incremental deploy diff.
// Fallback: add new columns via raw ALTER TABLE, then update cds_model cache
// manually so CDS knows about the new columns on next run.
// ─────────────────────────────────────────────────────────────────────────────
async function addNewColumnsRaw(client, model) {
  const actualTables = await getActualTables(client);
  const addedColumns = []; // track what we added for cache update

  for (const [name, entity] of Object.entries(model.definitions)) {
    if (entity.kind !== "entity") continue;
    if (entity["@cds.persistence.skip"]) continue;

    const table = name.replace(/\./g, "_").toLowerCase();
    if (!actualTables.has(table)) continue;

    const actualCols = await getTableColumns(client, table);
    const elements = entity.elements || {};

    for (const [colName, element] of Object.entries(elements)) {
      if (element.virtual) continue;
      if (element.type === "cds.Composition") continue;

      let dbCol, sqlType;

      if (element.type === "cds.Association") {
        if (!element.keys) continue;
        dbCol = (colName + "_id").toLowerCase();
        sqlType = "VARCHAR(36)";
      } else if (element.type) {
        dbCol = colName.toLowerCase();
        sqlType = resolveSqlType(element, model);
      } else {
        continue;
      }

      if (SYSTEM_COLUMNS.has(dbCol)) continue;
      if (actualCols.has(dbCol)) continue;

      console.log(`  ➕ Adding column: ${table}.${dbCol} (${sqlType})`);
      try {
        await client.query(
          `ALTER TABLE "${table}" ADD COLUMN IF NOT EXISTS "${dbCol}" ${sqlType}`,
        );
        addedColumns.push({ entityName: name, colName, dbCol, element });
      } catch (e) {
        console.warn(
          `  ⚠️  Could not add ${table}.${dbCol}: ${e.message.trim()}`,
        );
      }
    }
  }

  return addedColumns;
}

async function updateCdsModelCacheWithNewColumns(client, model, addedColumns) {
  if (addedColumns.length === 0) return;

  console.log("\n  Updating CDS model cache with new columns...");
  try {
    const tableCheck = await client.query(`
      SELECT COUNT(*) as count FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = 'cds_model'
    `);
    if (tableCheck.rows[0].count === "0") {
      console.log("  ⚠️  No cds_model table found, skipping cache update.");
      return;
    }

    const countCheck = await client.query(
      `SELECT COUNT(*) as count FROM cds_model`,
    );
    if (parseInt(countCheck.rows[0].count) === 0) {
      console.log("  ⚠️  cds_model is empty, skipping cache update.");
      return;
    }

    const { rows } = await client.query(`SELECT csn FROM cds_model LIMIT 1`);
    const storedCsn = JSON.parse(rows[0].csn);

    // For each added column, inject the element definition into the stored CSN
    // so CDS sees the column as part of the model on next run.
    for (const { entityName, colName, element } of addedColumns) {
      const entityDef = storedCsn.definitions?.[entityName];
      if (!entityDef) {
        // Entity not yet in cache (new table) — inject minimal entity definition
        storedCsn.definitions = storedCsn.definitions || {};
        const liveEntity = model.definitions[entityName];
        storedCsn.definitions[entityName] = JSON.parse(
          JSON.stringify(liveEntity),
        );
        console.log(`  ✅ Injected new entity into cache: ${entityName}`);
        continue;
      }

      // Entity exists in cache — just add the missing element
      entityDef.elements = entityDef.elements || {};
      if (!entityDef.elements[colName]) {
        entityDef.elements[colName] = JSON.parse(
          JSON.stringify(model.definitions[entityName].elements[colName]),
        );
        console.log(`  ✅ Injected into cache: ${entityName}.${colName}`);
      }
    }

    await client.query(`UPDATE cds_model SET csn = $1`, [
      JSON.stringify(storedCsn),
    ]);
    console.log("  ✅ CDS model cache updated with new columns.");
  } catch (e) {
    console.warn(`  ⚠️  Could not update CDS model cache: ${e.message.trim()}`);
    console.log(
      "  This is non-fatal — columns exist in DB, cache will self-heal on next fresh deploy.",
    );
  }
}

async function runCdsDeploy(client, model) {
  console.log("\n[5/6] Running CDS deploy...");
  try {
    const db = await cds.connect.to("db");
    await cds.deploy(model).to(db);
    console.log("  ✅ CDS deploy done!");
  } catch (e) {
    if (
      e.message.includes("Dropping tables is not supported") ||
      e.message.includes("Dropping elements is not supported")
    ) {
      console.log("  ✅ CDS deploy done! (removals handled manually)");
    } else if (e.message.includes("Unexpected non-primitive type")) {
      // Named enum type bug — CDS compiler can't handle the diff
      // Fall back to raw SQL for new columns + update cache manually
      console.log(
        "  ⚠️  CDS compiler enum bug hit, falling back to raw SQL...",
      );
      const addedColumns = await addNewColumnsRaw(client, model);
      await updateCdsModelCacheWithNewColumns(client, model, addedColumns);
      if (addedColumns.length === 0) {
        console.log("  ✅ No new columns needed, nothing to add.");
      } else {
        console.log(`  ✅ ${addedColumns.length} column(s) added via raw SQL.`);
      }
    } else {
      throw e;
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// STEP 6 — Apply unique constraints
// Skips constraints that already exist.
// ─────────────────────────────────────────────────────────────────────────────
async function applyUniqueConstraints(client) {
  console.log("\n[6/6] Applying unique constraints...");
  for (const { table, name, cols } of UNIQUE_CONSTRAINTS) {
    try {
      await client.query(
        `ALTER TABLE "${table}" ADD CONSTRAINT ${name} UNIQUE (${cols})`,
      );
      console.log(`  ✅ ${name}`);
    } catch (e) {
      if (e.message.includes("already exists")) {
        console.log(`  ⏭️  ${name} already exists, skipping`);
      } else {
        console.warn(`  ⚠️  ${name} failed: ${e.message.trim()}`);
      }
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────────────────────────────────────
async function main() {
  const client = new Client({
    host: process.env.DB_HOST,
    port: parseInt(process.env.DB_PORT),
    database: process.env.DB_NAME,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    ssl: { rejectUnauthorized: false },
  });

  await client.connect();

  console.log("Loading CDS model...");
  const rawModel = await cds.load(["db/schema.cds", "srv/service.cds"]);
  // Compile to inferred flavor — expands includes, generates FK columns (state_ID etc.),
  // resolves named enum types (TrailType → cds.String) so column diff is accurate.
  // API varies by @sap/cds version — try each flavor in order.
  let model;
  if (typeof cds.compile?.for?.inferred === "function") {
    model = cds.compile.for.inferred(rawModel);
  } else if (typeof cds.compile?.to?.inferred === "function") {
    model = cds.compile.to.inferred(rawModel);
  } else if (typeof cds.linked === "function") {
    model = cds.linked(rawModel);
  } else {
    model = rawModel;
  }
  console.log("Reading current DB schema...");

  await dropRemovedTables(client, model); // Step 1 — drop removed tables first
  await detectNewTables(client, model); // Step 2 — log new tables
  await syncColumns(client, model); // Step 3 — drop removed columns
  await patchCdsModelCache(client, model); // Step 4 — patch cache before deploy
  await runCdsDeploy(client, model); // Step 5 — CDS deploy or raw SQL fallback
  await applyUniqueConstraints(client); // Step 6 — enforce uniqueness

  await client.end();
  console.log("\n✅ Migration complete — no data lost!");
  process.exit(0);
}

main().catch((e) => {
  console.error("\nFAILED:", e.message);
  process.exit(1);
});
